import type { Buffer } from "node:buffer";

export interface FallbackResult {
  buffer: Buffer;
  mimeType: string;
  provider: string;
  sourceUrl: string;
  genre: string;       // matched genre slug from GENRES
  staticSlug: string;  // static.photos slug used for category
}

export interface FallbackProvider {
  name: string;
  fetch(prompt: string, promptVector: number[]): Promise<FallbackResult | null>;
}

export interface Genre {
  slug: string;       // genre identifier (kebab-case)
  staticSlug: string; // maps to a static.photos URL slug
  keywords: string[];
}

// All 106 genres from https://en.wikipedia.org/wiki/Category:Photography_by_genre
export const GENRES: Genre[] = [
  { slug: "360-product-photography",      staticSlug: "retail",       keywords: ["360 product", "360", "product photography", "product", "turntable", "ecommerce", "packshot"] },
  { slug: "abstract-photography",         staticSlug: "abstract",     keywords: ["abstract", "abstract photography", "non-representational", "art", "pattern", "shape", "texture", "geometric", "experimental"] },
  { slug: "action-shot",                  staticSlug: "sport",        keywords: ["action", "actionshot", "action shot", "motion blur", "freeze", "sport", "dynamic", "fast", "movement"] },
  { slug: "aerial-photography",           staticSlug: "aerial",       keywords: ["aerial", "aerial photography", "drone", "overhead", "top view", "bird's eye", "above", "altitude", "elevation"] },
  { slug: "air-to-air-photography",       staticSlug: "aerial",       keywords: ["air-to-air", "aircraft", "airplane", "jet", "formation", "flight", "aviation", "airborne"] },
  { slug: "analog-photography",           staticSlug: "vintage",      keywords: ["analog", "analogue", "film", "35mm", "darkroom", "chemical", "film roll", "negative", "silver halide"] },
  { slug: "architectural-photography",    staticSlug: "estate",       keywords: ["architectural", "architecture", "building", "structure", "facade", "interior design", "exterior", "blueprint", "design"] },
  { slug: "astrophotography",             staticSlug: "science",      keywords: ["astrophotography", "astro", "astronomy", "telescope", "space", "galaxy", "nebula", "stars", "deep sky", "milky way", "cosmos", "celestial"] },
  { slug: "aviation-photography",         staticSlug: "aerial",       keywords: ["aviation", "airplane", "aircraft", "airport", "runway", "pilot", "cockpit", "jet", "helicopter", "flight"] },
  { slug: "banquet-photography",          staticSlug: "event",        keywords: ["banquet", "gala", "dinner", "formal event", "reception", "hall", "wedding reception", "corporate dinner", "catering"] },
  { slug: "blind-photography",            staticSlug: "abstract",     keywords: ["blind", "unseen", "surprise", "random", "instinctive", "intuitive photography", "spontaneous"] },
  { slug: "candid-photography",           staticSlug: "people",       keywords: ["candid", "candid photography", "unposed", "natural", "spontaneous", "street", "real moment", "unstaged", "paparazzi"] },
  { slug: "close-up",                     staticSlug: "science",      keywords: ["close-up", "closeup", "close up", "detail", "magnify", "macro", "zoom", "tight shot", "focus"] },
  { slug: "cloudscape-photography",       staticSlug: "nature",       keywords: ["cloudscape", "cloud", "sky", "overcast", "storm cloud", "cumulus", "nimbus", "weather", "atmospheric"] },
  { slug: "conceptual-photography",       staticSlug: "abstract",     keywords: ["conceptual", "concept", "idea", "symbolic", "metaphor", "surreal", "fine art", "artistic statement", "creative concept"] },
  { slug: "concert-photography",          staticSlug: "event",        keywords: ["concert", "live music", "band", "stage", "performer", "musician", "crowd", "festival", "gig", "show", "spotlight"] },
  { slug: "conservation-photography",     staticSlug: "nature",       keywords: ["conservation", "wildlife conservation", "environmental", "ecosystem", "endangered", "habitat", "protect", "nature conservation"] },
  { slug: "cursed-image",                 staticSlug: "abstract",     keywords: ["cursed", "unsettling", "weird", "eerie", "disturbing", "odd", "bizarre", "uncanny", "strange photo"] },
  { slug: "die-shot",                     staticSlug: "technology",   keywords: ["die shot", "die", "chip", "semiconductor", "integrated circuit", "cpu", "processor", "silicon wafer", "micro chip"] },
  { slug: "dog-shaming",                  staticSlug: "people",       keywords: ["dog shaming", "pet", "dog", "animal misbehave", "sign", "funny pet", "meme"] },
  { slug: "eclipse-photography",          staticSlug: "science",      keywords: ["eclipse", "solar eclipse", "lunar eclipse", "totality", "corona", "sun", "moon", "shadow", "astronomical event"] },
  { slug: "event-photography",            staticSlug: "event",        keywords: ["event", "event photography", "ceremony", "gathering", "conference", "meeting", "awards", "launch", "occasion"] },
  { slug: "fancy-portrait",               staticSlug: "studio",       keywords: ["fancy portrait", "formal portrait", "dressed up", "costume", "period portrait", "elaborate", "fine portrait"] },
  { slug: "fashion-photography",          staticSlug: "cosmetic",     keywords: ["fashion", "fashion photography", "model", "runway", "editorial", "clothing", "style", "wardrobe", "designer", "couture", "vogue"] },
  { slug: "femto-photography",            staticSlug: "science",      keywords: ["femto", "femtosecond", "ultra-fast", "light propagation", "trillion fps", "slow light", "scientific imaging"] },
  { slug: "film-still",                   staticSlug: "studio",       keywords: ["film still", "movie still", "cinema", "behind the scenes", "set photo", "screenshot", "frame", "director", "scene"] },
  { slug: "fine-art-photography",         staticSlug: "abstract",     keywords: ["fine art", "fine-art photography", "gallery", "museum", "artistic", "expressive", "creative", "aesthetic", "art print"] },
  { slug: "fire-photography",             staticSlug: "red",          keywords: ["fire", "flame", "blaze", "burning", "inferno", "campfire", "wildfire", "heat", "combustion", "spark"] },
  { slug: "fireworks-photography",        staticSlug: "red",          keywords: ["fireworks", "firework", "pyrotechnic", "explosion", "celebration", "new year", "4th of july", "sparkle", "night fireworks"] },
  { slug: "food-photography",             staticSlug: "food",         keywords: ["food", "food photography", "dish", "meal", "cuisine", "plating", "ingredient", "culinary", "gourmet", "recipe"] },
  { slug: "food-photography-social-media",staticSlug: "food",         keywords: ["food social media", "instagram food", "flatlay", "food blog", "foodie", "overhead food", "aesthetic food", "trending food"] },
  { slug: "forensic-photography",         staticSlug: "legal",        keywords: ["forensic", "forensic photography", "crime scene", "evidence", "investigation", "police", "court", "criminal", "detective"] },
  { slug: "found-photography",            staticSlug: "vintage",      keywords: ["found photography", "found photo", "discovered photo", "vernacular", "anonymous", "old photo", "flea market photo"] },
  { slug: "genre-art",                    staticSlug: "abstract",     keywords: ["genre art", "genre scene", "everyday life", "genre painting", "narrative art", "storytelling", "scene"] },
  { slug: "geophotography",               staticSlug: "nature",       keywords: ["geophotography", "geology", "earth", "rock formation", "landscape", "geographic", "terrain", "topography", "land"] },
  { slug: "glamour-photography",          staticSlug: "cosmetic",     keywords: ["glamour", "glamour photography", "sensual", "alluring", "beauty", "pin-up", "boudoir", "elegant", "seductive"] },
  { slug: "high-key",                     staticSlug: "white",        keywords: ["high key", "highkey", "bright", "overexposed", "white tones", "soft light", "airy", "light background", "luminous"] },
  { slug: "high-speed-photography",       staticSlug: "technology",   keywords: ["high-speed", "high speed photography", "freeze motion", "water drop", "bullet", "splash", "strobe", "fast shutter", "microsecond"] },
  { slug: "imagery-intelligence",         staticSlug: "aerial",       keywords: ["imagery intelligence", "reconnaissance", "surveillance", "satellite imagery", "geospatial", "spy", "intelligence", "overhead surveillance"] },
  { slug: "impressionist-photography",    staticSlug: "blurred",      keywords: ["impressionist photography", "impressionist", "painterly", "soft", "dreamy", "pictorialist", "blended", "motion blur art"] },
  { slug: "kirlian-photography",          staticSlug: "wellness",     keywords: ["kirlian", "aura", "electromagnetic", "corona discharge", "energy field", "bioelectrography", "spirit photography"] },
  { slug: "lifestyle-photography",        staticSlug: "people",       keywords: ["lifestyle", "lifestyle photography", "daily life", "candid living", "authentic", "real life", "family", "couple", "everyday"] },
  { slug: "lo-fi-photography",            staticSlug: "vintage",      keywords: ["lo-fi", "lofi", "low fidelity", "grainy", "cheap camera", "toy camera", "low quality aesthetic", "imperfect"] },
  { slug: "lolcat",                       staticSlug: "people",       keywords: ["lolcat", "meme", "cat meme", "funny cat", "internet meme", "humorous", "viral photo"] },
  { slug: "lomography",                   staticSlug: "vintage",      keywords: ["lomography", "lomo", "lomographic", "holga", "diana", "vignette", "light leak", "cross process", "plastic lens"] },
  { slug: "long-exposure-photography",    staticSlug: "science",      keywords: ["long exposure", "long-exposure", "light trail", "car trail", "silk water", "star trail", "slow shutter", "nightscape", "light painting"] },
  { slug: "low-key",                      staticSlug: "black",        keywords: ["low key", "lowkey", "dark", "shadow", "moody", "dramatic", "chiaroscuro", "underexposed", "noir", "deep shadow"] },
  { slug: "low-key-photography",          staticSlug: "black",        keywords: ["low-key photography", "dark portrait", "rembrandt lighting", "split lighting", "dramatic light", "dark background"] },
  { slug: "macro-photography",            staticSlug: "science",      keywords: ["macro", "macro photography", "extreme close-up", "magnification", "insect", "flower detail", "1:1", "extension tube", "ring flash"] },
  { slug: "medical-photography",          staticSlug: "medical",      keywords: ["medical photography", "clinical photography", "surgical", "pathology", "dermatology", "anatomy", "patient", "healthcare imaging"] },
  { slug: "minimalist-photography",       staticSlug: "minimal",      keywords: ["minimalist photography", "minimalism", "negative space", "clean", "simple", "sparse", "less is more", "uncluttered"] },
  { slug: "monochrome-photography",       staticSlug: "monochrome",   keywords: ["monochrome", "black and white", "grayscale", "bnw", "bw", "mono", "desaturated", "silver", "tonal"] },
  { slug: "mug-shot",                     staticSlug: "legal",        keywords: ["mug shot", "mugshot", "booking photo", "arrest", "criminal record", "police photo", "id photo", "wanted"] },
  { slug: "narrative-photography",        staticSlug: "people",       keywords: ["narrative", "storytelling photography", "photo story", "series", "photographic narrative", "documentary story", "visual narrative"] },
  { slug: "new-topographics",             staticSlug: "outdoor",      keywords: ["new topographics", "topographic", "man-altered landscape", "industrial landscape", "suburban", "mundane", "banal landscape"] },
  { slug: "night-photography",            staticSlug: "black",        keywords: ["night photography", "night", "nocturnal", "low light", "city lights", "nightscape", "dark sky", "astrophotography night"] },
  { slug: "old-time-photography",         staticSlug: "vintage",      keywords: ["old-time photography", "old time photo", "historical costume", "period dress", "vintage portrait", "sepia", "daguerreotype"] },
  { slug: "panorama",                     staticSlug: "aerial",       keywords: ["panorama", "panoramic", "wide angle", "360 view", "landscape panorama", "stitched", "wide scene"] },
  { slug: "panoramic-photography",        staticSlug: "aerial",       keywords: ["panoramic photography", "wide panorama", "360 panorama", "vr panorama", "cylindrical", "spherical panorama"] },
  { slug: "photobiography",               staticSlug: "people",       keywords: ["photobiography", "photo biography", "life story", "memoir", "biographical", "documentary life", "personal archive"] },
  { slug: "photobombing",                 staticSlug: "people",       keywords: ["photobombing", "photobomb", "unexpected", "background surprise", "ruined photo", "uninvited", "funny background"] },
  { slug: "photography-indigenous-peoples",staticSlug: "people",      keywords: ["indigenous", "native", "tribal", "ethnic", "cultural", "traditional community", "anthropology", "heritage"] },
  { slug: "photojournalism",              staticSlug: "people",       keywords: ["photojournalism", "news photography", "press photo", "journalist", "breaking news", "documentary", "current events", "war photography"] },
  { slug: "photovoice",                   staticSlug: "people",       keywords: ["photovoice", "community photography", "empowerment", "social change", "participatory", "advocacy", "grassroots"] },
  { slug: "photowalking",                 staticSlug: "travel",       keywords: ["photowalking", "photowalk", "photo walk", "walking photography", "urban exploration", "street walk", "city walk"] },
  { slug: "pictorialism",                 staticSlug: "vintage",      keywords: ["pictorialism", "pictorialist", "soft focus artistic", "painterly photography", "gum print", "platinum print", "art photography movement"] },
  { slug: "polaroid-art",                 staticSlug: "vintage",      keywords: ["polaroid", "instant photo", "polaroid art", "impossible project", "instax", "instant film", "analog instant"] },
  { slug: "portrait-photography",         staticSlug: "people",       keywords: ["portrait", "portrait photography", "headshot", "face", "expression", "character", "subject", "likeness", "pose"] },
  { slug: "post-mortem-photography",      staticSlug: "vintage",      keywords: ["post-mortem", "postmortem photography", "memorial photography", "victorian death photo", "memorial portrait"] },
  { slug: "red-shirt-photography",        staticSlug: "people",       keywords: ["red shirt", "red shirt photography", "posed group", "staged crowd", "uniform group", "corporate group photo"] },
  { slug: "rogues-gallery",               staticSlug: "legal",        keywords: ["rogues gallery", "rogue", "criminal collection", "mug shot collection", "police archive", "wanted photos"] },
  { slug: "ruins-photography",            staticSlug: "outdoor",      keywords: ["ruins", "ruin", "abandoned", "decay", "urban exploration", "urbex", "derelict", "ghost town", "lost place", "crumbling"] },
  { slug: "satellite-imagery",            staticSlug: "aerial",       keywords: ["satellite imagery", "satellite", "remote sensing", "geospatial", "earth observation", "aerial map", "google earth", "landsat"] },
  { slug: "secret-photography",           staticSlug: "people",       keywords: ["secret photography", "covert", "hidden camera", "surveillance", "spy photography", "candid secret", "paparazzi"] },
  { slug: "self-portrait",                staticSlug: "people",       keywords: ["self portrait", "selfie", "self-portrait", "self photo", "autobiographical", "mirror shot", "self documentation"] },
  { slug: "skate-photography",            staticSlug: "sport",        keywords: ["skate", "skateboarding", "skater", "trick", "halfpipe", "grind", "kickflip", "ollie", "skate park", "urban skate"] },
  { slug: "slow-photography",             staticSlug: "blurred",      keywords: ["slow photography", "slow shutter", "motion blur", "panning", "intentional camera movement", "icm", "blurred motion"] },
  { slug: "snapshot-photography",         staticSlug: "people",       keywords: ["snapshot", "snapshot photography", "casual photo", "family snapshot", "amateur", "point and shoot", "memory"] },
  { slug: "social-photography",           staticSlug: "people",       keywords: ["social photography", "social media", "instagram", "facebook", "shared photo", "community photo", "social network"] },
  { slug: "soft-focus",                   staticSlug: "blurred",      keywords: ["soft focus", "soft lens", "diffused", "gentle blur", "dreamy", "romantic soft", "fog filter", "haze"] },
  { slug: "spirit-photography",           staticSlug: "wellness",     keywords: ["spirit photography", "ghost", "double exposure", "séance", "paranormal", "apparition", "spirit", "ectoplasm"] },
  { slug: "staged-photography",           staticSlug: "studio",       keywords: ["staged photography", "directed", "constructed", "tableaux", "setup", "arranged", "theatrical photography", "cinematic"] },
  { slug: "star-trail",                   staticSlug: "science",      keywords: ["star trail", "startrail", "star trails", "long exposure stars", "earth rotation", "polar star", "night sky rotation", "celestial motion"] },
  { slug: "still-life-photography",       staticSlug: "minimal",      keywords: ["still life", "still-life photography", "object", "arrangement", "tabletop", "product still", "flat lay", "composed objects"] },
  { slug: "straight-photography",         staticSlug: "abstract",     keywords: ["straight photography", "purist", "unmanipulated", "documentary style", "realist", "no darkroom", "f/64", "zone system"] },
  { slug: "street-photography",           staticSlug: "cityscape",    keywords: ["street photography", "street", "urban", "candid street", "public space", "city life", "pedestrian", "sidewalk", "urban candid"] },
  { slug: "subminiature-photography",     staticSlug: "vintage",      keywords: ["subminiature", "subminiature camera", "minox", "spy camera", "miniature film", "tiny camera", "micro format"] },
  { slug: "theatre-photography",          staticSlug: "event",        keywords: ["theatre", "theater photography", "stage", "performance", "actor", "play", "opera", "dance performance", "spotlight stage"] },
  { slug: "thoughtography",               staticSlug: "wellness",     keywords: ["thoughtography", "psychic photography", "projected thought", "nensha", "paranormal image", "psychokinesis photo"] },
  { slug: "time-lapse-photography",       staticSlug: "season",       keywords: ["time-lapse", "timelapse", "time lapse photography", "hyperlapse", "flower blooming", "cloud movement", "day to night"] },
  { slug: "travel-photography",           staticSlug: "travel",       keywords: ["travel", "travel photography", "trip", "destination", "explore", "adventure", "landmark", "culture", "tourism", "wanderlust", "globe"] },
  { slug: "ultraviolet-photography",      staticSlug: "science",      keywords: ["ultraviolet photography", "uv photography", "uv light", "fluorescence", "black light", "invisible spectrum", "uv fluorescent"] },
  { slug: "underwater-photography",       staticSlug: "blue",         keywords: ["underwater photography", "underwater", "scuba", "dive", "ocean floor", "coral reef", "marine life", "aquatic", "sub-aqua"] },
  { slug: "underwater-videography",       staticSlug: "blue",         keywords: ["underwater videography", "underwater video", "underwater film", "dive video", "ocean documentary", "marine video"] },
  { slug: "vernacular-photography",       staticSlug: "people",       keywords: ["vernacular photography", "everyday photo", "amateur snapshot", "found vernacular", "ordinary", "mundane photo", "home photo"] },
  { slug: "vintage-print",               staticSlug: "vintage",      keywords: ["vintage print", "antique photo", "old print", "historical photograph", "archival", "faded", "sepia tone", "albumen print"] },
  { slug: "virtual-photography",          staticSlug: "gaming",       keywords: ["virtual photography", "video game photography", "in-game photo", "screenshot art", "game world", "photomode", "digital photography"] },
  { slug: "visual-anthropology",          staticSlug: "people",       keywords: ["visual anthropology", "ethnographic photography", "cultural documentation", "anthropology", "tribe", "indigenous culture", "fieldwork"] },
  { slug: "vr-photography",               staticSlug: "gaming",       keywords: ["vr photography", "virtual reality photography", "360 vr", "immersive photo", "vr tour", "360 image", "360 degree"] },
  { slug: "wedding-photography",          staticSlug: "event",        keywords: ["wedding photography", "wedding", "bride", "groom", "ceremony", "nuptials", "reception", "marriage", "bridal", "engagement"] },
  { slug: "tele-snaps",                   staticSlug: "vintage",      keywords: ["tele-snaps", "telesnaps", "tv screenshot", "television capture", "off-screen photo", "broadcast still", "tv still"] },
  { slug: "photo-op",                     staticSlug: "people",       keywords: ["photo op", "photo opportunity", "posed photo", "publicity photo", "press photo opportunity", "meet and greet photo"] },
  { slug: "paris-in-motion",              staticSlug: "travel",       keywords: ["paris", "paris photography", "city of light", "eiffel", "seine", "montmartre", "french street photography"] },
  { slug: "isap",                         staticSlug: "aerial",       keywords: ["international society aviation photography", "isap", "aviation society", "airshow photography", "aviation club"] },
  { slug: "erotic-photography",           staticSlug: "studio",       keywords: ["erotic", "nude", "boudoir", "intimate", "sensual portrait", "body photography", "figure study"] },
  { slug: "humanist-photography",         staticSlug: "people",       keywords: ["humanist photography", "humanism", "humanist", "human condition", "social documentary", "people centered", "dignity"] },
];
